services:
  tvone:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/tvone &&
      rm -rf /hls/sctv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.2:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/tvone/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/tvone/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  kompastv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/kompastv &&
      rm -rf /hls/sctv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.17:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/kompastv/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/kompastv/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  cnbc_indonesia:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/cnbc_indonesia &&
      rm -rf /hls/sctv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.12:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/cnbc_indonesia/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/cnbc_indonesia/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  cnn_indonesia:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/cnn_indonesia &&
      rm -rf /hls/sctv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.13:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/cnn_indonesia/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/cnn_indonesia/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  metrotv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/metrotv &&
      rm -rf /hls/sctv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.24:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/metrotv/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/metrotv/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  sctv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/sctv &&
      rm -rf /hls/sctv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.29:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/sctv/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/sctv/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  indosiar:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/indosiar &&
      rm -rf /hls/indosiar/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.28:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/indosiar/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/indosiar/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  antv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/antv &&
      rm -rf /hls/antv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.15:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/antv/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/antv/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  transtv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/transtv &&
      rm -rf /hls/transtv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.10:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/transtv/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/transtv/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  trans7:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/trans7 &&
      rm -rf /hls/trans7/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.11:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/trans7/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/trans7/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  mdtv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/mdtv &&
      rm -rf /hls/mdtv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.14:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/mdtv/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/mdtv/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s

  rtv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/rtv &&
      rm -rf /hls/rtv/* &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.23:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/rtv/index.m3u8'"
    healthcheck:
      test: >
        /bin/sh -c '
          f="/hls/rtv/index.m3u8";
          [ -f "$f" ] || exit 1;
          now=$(date +%s);
          mod=$(stat -c %Y "$f");
          diff=$((now - mod));
          [ "$diff" -le 10 ] || exit 1
        '
      interval: 8s
      timeout: 2s
      retries: 2
      start_period: 20s
