services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./config/origin/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/ramdisk:/hls:ro
    ports:
      - "80:80"

  rcti:
    image: yuspynoza/rctiplus-go:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    command: -O /hls/rcti "http://rctiplus.hexafiber.net/rcti.m3u8"

  mnctv:
    image: yuspynoza/rctiplus-go:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    command: -O /hls/mnctv "http://rctiplus.hexafiber.net/mnctv.m3u8"

  gtv:
    image: yuspynoza/rctiplus-go:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    command: -O /hls/gtv "http://rctiplus.hexafiber.net/gtv.m3u8"

  inews:
    image: yuspynoza/rctiplus-go:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    command: -O /hls/inews "http://rctiplus.hexafiber.net/inews.m3u8"

  kompastv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/kompastv &&
      exec ffmpeg
      -hide_banner -loglevel warning
      -re -i 'udp://239.2.2.17:3000'
      -c:v copy
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1
      -f hls
      -hls_time 2
      -hls_list_size 20
      -hls_flags delete_segments+append_list
      -hls_segment_filename /hls/kompastv/seg_%d.ts
      /hls/kompastv/index.m3u8"

  tvone:
    image: restreamio/gstreamer:2025-06-18T18-00-49Z-prod
    restart: unless-stopped
    network_mode: host # Butuh untuk join multicast dari host, atau atur --cap-add=NET_ADMIN
    volumes:
      - /tmp/ramdisk:/hls
    command: >
     /bin/sh -c "mkdir -p /hls/tvone &&
      exec gst-launch-1.0 -e
      udpsrc multicast-group=239.2.2.2 port=3000 buffer-size=2097152 !
      queue max-size-bytes=0 max-size-buffers=0 max-size-time=2000000000 !
      tsdemux name=demux
        demux.audio_0 ! queue ! mpegaudioparse ! avdec_mp2float ! audioconvert ! voaacenc bitrate=128000 ! aacparse ! mux.
        demux.video_0 ! queue ! h264parse ! mux.
      mpegtsmux name=mux !
      hlssink max-files=6 target-duration=4
      location=/hls/tvone/segment%05d.ts playlist-location=/hls/tvone/index.m3u8"
