services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./config/origin/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/ramdisk:/hls:ro
    ports:
      - "80:80"
