services:
  tvone:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/tvone &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.2:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/tvone/index.m3u8'"

  kompastv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/kompastv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.17:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/kompastv/index.m3u8'"

  cnbc_indonesia:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/cnbc_indonesia &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.12:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/cnbc_indonesia/index.m3u8'"

  cnn_indonesia:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/cnn_indonesia &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.13:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/cnn_indonesia/index.m3u8'"

  metrotv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/metrotv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.24:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/metrotv/index.m3u8'"

  bn_channel:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/bn_channel &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.25:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/bn_channel/index.m3u8'"

  sctv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/sctv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.29:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/sctv/index.m3u8'"

  indosiar:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/indosiar &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.28:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/indosiar/index.m3u8'"

  tvri_nasional:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/tvri_nasional &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.7:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/tvri_nasional/index.m3u8'"

  tvri_world:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/tvri_world &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.8:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/tvri_world/index.m3u8'"

  tvri_sport:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/tvri_sport &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.9:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/tvri_sport/index.m3u8'"

  antv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/antv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.15:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/antv/index.m3u8'"

  transtv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/transtv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.10:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/transtv/index.m3u8'"

  trans7:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/trans7 &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.11:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/trans7/index.m3u8'"

  mdtv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/mdtv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.14:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/mdtv/index.m3u8'"

  moji:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/moji &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.5:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/moji/index.m3u8'"

  rtv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/rtv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.23:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/rtv/index.m3u8'"

  vtv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/vtv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.16:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/vtv/index.m3u8'"

  daai_tv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/daai_tv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.34:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/daai_tv/index.m3u8'"

  mentari_tv:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/mentari_tv &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.6:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/mentari_tv/index.m3u8'"

  rodja:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/rodja &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.31:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/rodja/index.m3u8'"

  mgi:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/mgi &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.32:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/mgi/index.m3u8'"

  ashiil:
    image: jrottenberg/ffmpeg:latest
    restart: unless-stopped
    volumes:
      - /tmp/ramdisk:/hls
    network_mode: "host"
    entrypoint: >
      /bin/sh -c "mkdir -p /hls/ashiil &&
      exec ffmpeg -hide_banner -loglevel warning \
      -analyzeduration 10000000 -probesize 10000000 \
      -re -i 'udp://239.2.2.33:3000?buffer_size=2097152' \
      -c:v copy \
      -c:a aac -profile:a aac_low -b:a 64k -ar 32000 -ac 1 \
      -f hls \
      -hls_time 6 \
      -hls_list_size 10 \
      -hls_flags delete_segments \
      '/hls/ashiil/index.m3u8'"
